### ISSUE TITLE
Websocket error abortHandshake

### ISSUE THREAD

**Issue by lechim** [binary-com/binary-live-api#149]
I want to convert all my nodejs projects from using the api to using this api wrapper. But I cannot get past the first connection with this package.

I keep getting errors with the demo using yarn and npm:

yarn run v1.22.4
$ node node-demo.js
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 401
    at ClientRequest.<anonymous> (C:\Users\binary-live-api-master\binary-live-api-master\demos\node\node_modules\ws\lib\websocket.js:579:7)
    at ClientRequest.emit (events.js:311:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (C:\Users\binary-live-api-master\binary-live-api-master\demos\node\node_modules\ws\lib\websocket.js:693:15)
    at ClientRequest.<anonymous> (C:\Users\binary-live-api-master\binary-live-api-master\demos\node\node_modules\ws\lib\websocket.js:579:7)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

How can I fix this?

**Comment by wilburforce83** [comment]
@lechim do you mean the nodejs bot within the main repo?

Short answer is you can't really, there would be so much refactoring I'd just build you own node app. I have a very stable node app base. If you send me you email I can give you a copy. From that you can just write a strategy in node and drop in the start folder. It uses technical indicators npm so you can use anytging from that package for you strays,  or any vanilla or stats lite functions

**Comment by lechim** [comment]
@wilburforce83 Yeah it seams to me that will be the case. I do not really want to rebuild it.

If you can send me a copy of that code base I will be able to try work from it. jeanm.steyn.01@gmail.com

Thank you.
