### ISSUE TITLE
LiveApi.resubscribe crashes

### ISSUE THREAD

**Issue by klausuhl** [binary-com/binary-live-api#33]
I have implemented a small node.js based test application that subscribes to a symbol and logs all tick events. However, after running for a while it always crashes with the below error message:
```
/home/ubuntu/binary-options-trader/node_modules/binary-live-api/lib/binary-live-api.js:389
                    this.subscribeToTicks(Object.keys(ticks));
                                                 ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at LiveApi.resubscribe (/home/ubuntu/binary-options-trader/node_modules/binary-live-api/lib/binary-live-api.js:389:43)
    at Timeout._onTimeout (/home/ubuntu/binary-options-trader/node_modules/binary-live-api/lib/binary-live-api.js:284:25)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

The ticks object is, actually, an empty dictionary, although it should contain one entry:
`LiveSubscriptions { state: { ticks: {}, proposals: {} } }`

**Comment by borisyankov** [comment]
I just rewrote the resubscribe code, and now this error is fixed.
If you have any other issues with it, please report again. Thanks.
